name: build and push
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: docker build & test (in Dockerfile)
      run: |
        version="$(date '+%Y-%m-%d')-$(git --no-pager log -1 --pretty=%h)"
        prefix=ghcr.io/${{github.repository}}
        docker image build -t ${prefix}:latest -t ${prefix}:${version} .
        echo "image_version=$version" >> $GITHUB_ENV
        echo "image_prefix=$prefix" >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker push
      run: |
        docker image push ${{ env.image_prefix }}:latest
        docker image push ${{ env.image_prefix }}:${{env.image_version}}
